# personnaliser le site à votre marque en remplaçant
# nom_intuition par le nom de votre intuition
# mon_equipe par le nom de votre équipe
# 
intuition: planurconv
nom_equipe: 2r
code_equipe: puc01

theme: jekyll-theme-dinky
